name: "execute with sver"
description: "execute with sver"

inputs:
  phase:
    description: 'phase name'
    required: true
  command:
    description: 'execute command'
    required: true
  path:
    description: 'sver target path'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Create ci-result dir
      run: mkdir ci-result
    - id: calc_version
      name: calc current version
      run: |
        version="$(sver calc ${{ inputs.path }})"
        echo "##[set-output name=version;]${version}"
    - name: cal
      run: mkdir ci-result
    - name: Cache ci result
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-ci-result-${{ steps.calc_version.outputs.version }}
        path: ci-result
    - name: Check ci-result
      id: ci_result
      run: |
        echo "##[set-output name=status;]$(test -f ci-result/${{ inputs.phase }}-${{ steps.calc_version.outputs.version }}.success ; echo $?)"
    - name: execute
      if: ${{ steps.ci_result.outputs.already_runned != 0 }}
      run: "${{ inputs.command }}"
    - name: save
      run: touch ci-result/${{ inputs.phase }}-${{ steps.calc_version.outputs.version }}.success
