name: "setup sver"
description: "setup sver"

inputs:
  version:
    description: 'sver release version'
    required: false
    default: 'v0.1.2'
  os:
    description: 'sver release os'
    required: false
    default: 'linux'

runs:
  using: "composite"
  steps:
    - name: install sver
      shell: bash
      run: |
        TEMPDIR=$(mktemp -d)
        cd $TEMPDIR
        wget "https://github.com/mitoma/sver/releases/download/${{ inputs.version }}/sver_${{ inputs.version }}_${{ inputs.os }}_amd64.zip"
        unzip sver_${{ inputs.version }}_${{ inputs.os }}_amd64.zip
        mv sver /usr/local/bin
        sver --help
