name: "execute with sver"
description: |
  すでに同じバージョンに対してジョブが未成功のときのみ実行する command を実行する。

inputs:
  phase:
    description: 'phase name'
    required: true
  command:
    description: 'execute command'
    required: true
  path:
    description: 'sver target path'
    required: false
    default: '.'

  github_token:
    description: 'github token for download artifact'
    required: true

  cache_key:
    description: 'cache key'
    required: false
    default: ''
  cache_path:
    description: 'cache path'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Create ci-result dir
      shell: bash
      run: mkdir -p ci-result
    - id: calc_version
      name: calc current version
      shell: bash
      run: |
        version="$(sver calc ${{ inputs.path }})"
        echo "##[set-output name=version;]${version}"

    - id: ci_result
      name: Download ci_result
      shell: bash
      run: |
        exit_code=0
        gh run download -n '${{ inputs.phase }}-${{ steps.calc_version.outputs.version }}.success' || exit_code=$?
        echo "##[set-output name=exit_code;]${exit_code}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: restore cache
      if: ${{ steps.ci_result.outputs.exit_code != '0' && inputs.cache_key != '' && inputs.cache_path != '' }}
      uses: actions/cache@v3
      with:
        key: "${{ inputs.cache_key }}"
        path: "${{ inputs.cache_path }}"

    - name: execute
      if: ${{ steps.ci_result.outputs.exit_code != '0' }}
      shell: bash
      run: "${{ inputs.command }}"

    - name: save result
      if: ${{ steps.ci_result.outputs.exit_code != '0' }}
      shell: bash
      run: touch ci-result/${{ inputs.phase }}-${{ steps.calc_version.outputs.version }}.success

    - uses: actions/upload-artifact@v3
      if: ${{ steps.ci_result.outputs.exit_code != '0' }}
      with:
        name: ${{ inputs.phase }}-${{ steps.calc_version.outputs.version }}.success
        path: ci-result/${{ inputs.phase }}-${{ steps.calc_version.outputs.version }}.success

    - name: echo skip log
      if: ${{ steps.ci_result.outputs.exit_code == '0' }}
      shell: bash
      run: echo "job is already succeeded. skip this job."
