name: "Continuous Integration"

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup and calc version
    - uses: ./.github/actions/setup_sver

    # ci phase
    - name: Build
      uses: ./.github/actions/exec_sver
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        phase: build
        command: cargo build --verbose
        cache_key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        cache_path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - name: Lint
      uses: ./.github/actions/exec_sver
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        phase: lint
        command: cargo clippy --verbose
        cache_key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        cache_path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - name: Test
      uses: ./.github/actions/exec_sver
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        phase: test
        command: cargo test --verbose
        cache_key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        cache_path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
