name: "Continuous Integration"

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  # check and build
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux
          - windows
          - macos
        include:
          - target: linux
            os: ubuntu-latest
          - target: windows
            os: windows-latest
          - target: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup_sver
        with:
          os: ${{ matrix.target }}

      # ci phase
      - name: check all
        uses: ./.github/actions/exec_sver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-${{ matrix.target }}
          command: |
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          cache_key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: ${{ runner.os }}-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

  # build and upload artifact
  build_artifact:

    # run on branch [main] or tag [v*]
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) }}
    needs: [build]

    strategy:
      fail-fast: false
      matrix:
        target:
          - linux
          - windows
          - macos
        include:
          - target: linux
            os: ubuntu-latest
          - target: windows
            os: windows-latest
          - target: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup_sver
        with:
          os: ${{ matrix.target }}

      # artifact phase
      - name: build artifact
        uses: ./.github/actions/exec_sver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: artifact-${{ matrix.target }}
          command: |
            cargo build --release
            mkdir artifact
            cd artifact
            cp ../LICENSE .
            cp ../README.md .
            if [ "${{ matrix.target }}" = "windows" ]; then
              cp ../target/release/sver.exe .
            else
              cp ../target/release/sver .
            fi
          cache_key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: ${{ runner.os }}-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          artifact_name: sver-${{ matrix.target }}
          artifact_path: artifact

  # release sver
  release_sver:
    # run on tag [v*]
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    needs: [build_artifact]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup_sver

      # artifact phase
      - id: calc_version
        name: calc current version
        run: |
          version="$(sver calc ${{ inputs.path }})"
          echo "##[set-output name=version;]${version}"

      - id: extract_tag
        name: Extract tag name
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: create release
        run: ./release.sh "${{ steps.extract_tag.outputs.tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
