on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup and calc version
    - uses: ./.github/actions/setup_sver

    # setup cache
    - name: Cache cargo dependency
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target

    # ci phase
    - name: Build
      uses: ./.github/actions/setup_sver
      with:
        phase: build
        command: cargo build --verbose
#    - name: Lint
#      if: ${{ steps.ci_result.outputs.lint != 0 }}
#      run: cargo clippy --verbose && touch ci-result/lint-${{ steps.calc_version.outputs.version }}.success
#    - name: Run tests
#      if: ${{ steps.ci_result.outputs.test != 0 }}
#      run: cargo test --verbose && touch ci-result/test-${{ steps.calc_version.outputs.version }}.success
