name: "Continuous Integration"

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup and calc version
    - uses: ./.github/actions/setup_sver

    # ci phase
    - name: check all
      uses: ./.github/actions/exec_sver
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        phase: check
        command: |
          cargo fmt --all -- --check
          cargo clippy --verbose -- -D warnings
          cargo build --verbose
          cargo test --verbose
        cache_key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        cache_path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
