on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup and calc version
    - uses: ./.github/actions/setup_sver

    # setup cache
    - name: Cache cargo dependency
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target

    # ci phase
    - name: Build
      uses: ./.github/actions/sver
      with:
        phase: build
        command: cargo build --verbose
    - name: Lint
      uses: ./.github/actions/sver
      with:
        phase: lint
        command: cargo clippy --verbose
    - name: Test
      uses: ./.github/actions/sver
      with:
        phase: test
        command: cargo test --verbose
