on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install sver
      run: |
        wget https://github.com/mitoma/sver/releases/download/v0.1.0/sver_linux_amd64.zip
        unzip sver_linux_amd64.zip
        mv sver_linux_amd64/sver /usr/local/bin
        rm -rf sver_linux_amd64.zip sver_linux_amd64
        sver --help
    - uses: actions/checkout@v3
    - id: calc_version
      name: calc current version
      run: |
        version="$(sver calc .)"
        echo "##[set-output name=version;]${version}"
    - name: Create ci-result dir
      run: mkdir ci-result
    - name: Build
      run: cargo build --verbose && touch ci-result/build-${{ steps.calc_version.outputs.version }}.success
    - name: Lint
      run: cargo clippy --verbose && touch ci-result/lint-${{ steps.calc_version.outputs.version }}.success
    - name: Run tests
      run: cargo test --verbose && touch ci-result/test-${{ steps.calc_version.outputs.version }}.success
    - name: upload ci-result artifact
      uses: actions/upload-artifact@v3
      with:
        name: ci-result
        path: ci-result/*
    - name: Print version
      run: echo "version=${{ steps.calc_version.outputs.version }}"